export const language = {
	en: {
		activity: `Activity`,
		assets: `Assets`,
		assetFetchFailed: `Failed to fetch asset`,
		blockHeight: `Block Height`,
		close: `Close`,
		collections: `Collections`,
		connect: `Connect`,
		copied: `Copied`,
		copyAddress: `Copy address`,
		dateCreated: `Date Created`,
		disconnect: `Disconnect`,
		fetching: `Fetching`,
		implements: `Implements`,
		learn: `Learn`,
		listings: `Listings`,
		overview: `Overview`,
		pageNotFound: `Page not found`,
		provenanceDetails: `Provenance Details`,
		transaction: `Transaction`,
		useDarkMode: `Use dark mode`,
		useLightMode: `Use light mode`,
		viewblock: `Viewblock`,
		viewProfile: `View profile`,
	},
};
