export const language = {
	en: {
		activity: `Activity`,
		activeListings: `Active listings`,
		activeSaleOrders: `Active Sale Orders`,
		arBridge: `Bridge AR`,
		arSwap: `Swap AO Tokens`,
		asset: `Asset`,
		assets: `Assets`,
		assetFetchFailed: `Failed to fetch asset`,
		assetsFetchFailed: `Failed to fetch assets`,
		assetRights: `Asset Rights`,
		assetQuantity: `Asset quantity`,
		assetQuantityInfo: `Slide for asset quantity`,
		balances: `Balances`,
		bio: `Bio`,
		blockHeight: `Block Height`,
		buy: `Buy`,
		cancel: `Cancel`,
		cancelOrder: `Cancel order`,
		close: `Close`,
		collection: `Collection`,
		collections: `Collections`,
		collectionFetchFailed: `Failed to fetch collection`,
		collectionsFetchFailed: `Failed to fetch collections`,
		comments: `Comments`,
		complete: `Complete`,
		confirmListing: `Confirm listing`,
		confirmOrderCancel: `Confirm order cancellation`,
		confirmOrderCancelInfo: `This will remove the active listing that you have created on this asset. The asset will be removed from the UCM and sent back to your profile.`,
		confirmPurchase: `Confirm purchase`,
		confirmTransfer: `Confirm transfer`,
		connect: `Connect`,
		connectWallet: `Connect your wallet`,
		connectToContinue: `Connect your wallet to continue`,
		copied: `Copied`,
		copyWalletAddress: `Copy wallet address`,
		copyProfileAddress: `Copy profile address`,
		create: `Create`,
		createProfile: `Create your profile`,
		createdBy: `Created by`,
		createdOn: `Created on`,
		currentlyBeingSoldBy: `Currently being sold by`,
		currentlyOwnedBy: `Currently owned by`,
		dailyRewards: `Daily rewards`,
		dateCreated: `Date Created`,
		dayCount: (count: number) => `${count} day${count > 1 ? 's' : ''}`,
		dayStreak: (length: string) => `${length} day streak`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		editProfile: `Edit profile`,
		error: `Error`,
		errorUpdatingProfile: `Error updating profile`,
		executing: `Executing`,
		fetching: `Fetching`,
		floorPrice: `Floor price`,
		goTo: `Go to`,
		implements: `Implements`,
		leaderboard: `Leaderboard`,
		learn: `Learn`,
		license: `License`,
		listing: `Listing`,
		listings: `Listings`,
		loading: `Loading`,
		market: `Market`,
		max: `Max`,
		maxCharsReached: `Max chars reached`,
		name: `Name`,
		next: `Next`,
		noAssetsFound: `No assets found`,
		noCollectionsFound: `No collections found`,
		noListings: `No listings`,
		orderProcessed: `Your order has been processed`,
		owner: `Owner`,
		overview: `Overview`,
		pageNotFound: `Page not found`,
		pasteFromClipboard: `Paste from clipboard`,
		percentage: `Percentage`,
		percentageListed: `Percentage listed`,
		previous: `Previous`,
		pixlBalanceInfo: `Your PIXL balance will show here`,
		pixlHoldings: `PIXL Holdings`,
		price: `Price`,
		profileCreated: `Profile created`,
		profileUpdated: `Profile updated`,
		profileCreatingInfo: `Creating profile`,
		provenanceDetails: `Provenance Details`,
		quantity: `Quantity`,
		recipient: `Recipient`,
		removeAvatar: `Remove avatar`,
		removeBanner: `Remove banner`,
		reviewOrderDetails: `Review your order details above`,
		save: `Save`,
		sell: `Sell`,
		seller: `Seller`,
		streak: `Streak`,
		streaks: `Streaks`,
		streakCountdown1: `You have approximately`,
		streakCountdown2: `Until you can continue building your streak`,
		streakCountdown3: `To continue building your streak`,
		streakLeaderboard: `Streak leaderboard`,
		streakStart: `Buy an asset today to start your streak`,
		streakTitle1: `Start your streak`,
		streakTitle2: `Getting warmer`,
		streakTitle3: `Building the flame`,
		streakTitle4: `Rising heat`,
		streakTitle5: `You're on fire`,
		title: `Title`,
		topCreators: `Top Creators`,
		totalAssets: `Total assets`,
		totalAssetBalance: `Total asset balance`,
		totalListingPercentage: `Total listing percentage`,
		totalListingQuantity: `Total listing quantity`,
		totalPrice: `Total price`,
		totalPurchasePercentage: `Total purchase percentage`,
		totalPurchaseQuantity: `Total purchase quantity`,
		totalTransferPercentage: `Total transfer percentage`,
		totalTransferQuantity: `Total transfer quantity`,
		totalSalesBalance: `Total balance for sale`,
		totalSalesPercentage: `Total percentage for sale`,
		totalSalesBalanceAvailable: `Total balance available for sale`,
		totalSalesPercentageAvailable: `Total percentage available for sale`,
		totalTransferBalanceAvailable: `Total balance available for transfer`,
		totalTransferPercentageAvailable: `Total percentage available for transfer`,
		transaction: `Transaction`,
		transfer: `Transfer`,
		unitPrice: `Unit price`,
		updating: `Updating`,
		updatingAsset: `Updating asset`,
		uploadAvatar: `Upload avatar`,
		uploadBanner: `Upload banner`,
		username: `Username`,
		usernameAsDisplayName: `Name will be the same as username`,
		useDarkDisplay: `Use dark display`,
		useLightDisplay: `Use light display`,
		viewAllCollections: `View all collections`,
		viewFullBio: `View full bio`,
		viewOnArweave: `View on Arweave`,
		viewProfile: `View profile`,
	},
};
