export const language = {
	en: {
		activity: `Activity`,
		activeListings: `Active Listings`,
		activeSaleOrders: `Active Sale Orders`,
		amountExceedsBalance: `Amount Exceeds Balance`,
		appError: `An Error Has Occurred. Please Check Back Soon.`,
		arBridge: `Bridge AR for Wrapped AR`,
		arSwap: `Swap AO Tokens`,
		asset: `Asset`,
		assets: `Assets`,
		assetFetchFailed: `Failed to Fetch Asset`,
		assetsFetchFailed: `Failed to Fetch Assets`,
		assetRights: `Asset Rights`,
		assetStamped: `Asset Stamped`,
		assetQuantity: `Asset Quantity`,
		assetQuantityInfo: `Slide for Asset Quantity`,
		back: `Back`,
		balances: `Balances`,
		bio: `Bio`,
		blockHeight: `Block Height`,
		buy: `Buy`,
		buyer: `Buyer`,
		cancel: `Cancel`,
		cancelOrder: `Cancel Order`,
		close: `Close`,
		collection: `Collection`,
		collections: `Collections`,
		collectionFetchFailed: `Failed to Fetch Collection`,
		collectionsFetchFailed: `Failed to Fetch Collections`,
		comments: `Comments`,
		complete: `Complete`,
		confirmListing: `Confirm Listing`,
		confirmOrderCancel: `Confirm Order Cancellation`,
		confirmOrderCancelInfo: `This will remove the active listing you have created on this asset. The amount the listing was created for will be transferred back to you.`,
		confirmPurchase: `Confirm Purchase`,
		confirmTransfer: `Confirm Transfer`,
		connect: `Connect`,
		connectWallet: `Connect Your Wallet`,
		connectWalletToStamp: `Connect a Wallet to Stamp`,
		connectToContinue: `Connect Your Wallet to Continue`,
		copied: `Copied`,
		copyPageUrl: `Copy URL`,
		copyProfileId: `Copy Profile ID`,
		copyWalletAddress: `Copy Wallet Address`,
		create: `Create`,
		createProfile: `Create Your Profile`,
		createProfileToContinue: `Create Your Profile to Continue`,
		createdBy: `Created By`,
		createdOn: `Created On`,
		currentOwners: `Current Owners`,
		currentlyBeingSoldBy: `Being Sold By`,
		currentlyOwnedBy: `Owned By`,
		dailyRewards: `Daily Rewards`,
		date: `Date`,
		dateCreated: `Date Created`,
		dayCount: (count: number) => `${count} Day${count > 1 ? 's' : ''}`,
		dayStreak: (length: string) => `${length} Day Streak`,
		description: `Description`,
		disconnect: `Disconnect`,
		dismiss: `Dismiss`,
		done: `Done`,
		editProfile: `Edit Profile`,
		error: `Error`,
		errorOccurred: `Error Occurred`,
		errorUpdatingProfile: `Error Updating Profile`,
		event: `Event`,
		executing: `Executing`,
		fetching: `Fetching`,
		fetchingAsset: `Fetching Asset`,
		fetchingProfile: `Fetching Profile`,
		fetchingTokenbalances: `Fetching Token Balances`,
		floorPrice: `Floor Price`,
		getWrappedAr: `Get wAR`,
		viewAr: `View AR`,
		gettingStamps: `Getting Your Stamps`,
		goTo: `Go To`,
		implements: `Implements`,
		interactions: `Interactions`,
		insufficientBalance: `Insufficient Balance`,
		lastUCMUpdate: `Last UCM Update`,
		leaderboard: `Leaderboard`,
		learn: `Learn`,
		learnMore: `Learn More Here`,
		license: `License`,
		listing: `Listing`,
		listings: `Listings`,
		loading: `Loading`,
		loadMore: `Load More`,
		market: `Market`,
		max: `Max`,
		maxCharsReached: `Max Chars Reached`,
		name: `Name`,
		next: `Next`,
		noAssetsFound: `No Assets Found`,
		noBio: `No Bio`,
		noCollectionsFound: `No Collections Found`,
		noActivity: `No Activity Found`,
		noListings: `No Listings`,
		nonTransferable: `This Asset Cannot Be Transferred`,
		orderCancelled: `Order Cancelled`,
		// Token conversion strings
		tokenConversionRequired: `Token Conversion Required`,
		conversionExplanation: `This Asset Is Not Available for Purchase with Your Selected Token. We Can Convert Your Tokens to Complete the Purchase.`,
		checkingConversionOptions: `Checking Conversion Options`,
		noConversionAvailable: `No Conversion Route Available for These Tokens`,
		proceedWithConversion: `Proceed with Conversion`,
		conversionRate: `Conversion Rate`,
		fees: `Fees`,
		slippage: `Slippage`,
		orderConfirmationDetailsListing: `Listing Confirmation Details`,
		orderConfirmationDetailsPurchase: `Purchase Confirmation Details`,
		orderConfirmationReviewListing: `Review Your Listing Details Above`,
		orderConfirmationReviewPurchase: `Review Your Purchase Details Above`,
		orderConfirmationReviewTransfer: `Review Your Transfer Details Above`,
		orderConfirmationInfo: `Order information will show here`,
		orderId: `Order ID`,
		orderProcessed: `Your Order Has Been Processed`,
		ordersUpdating: `Orders Are Being Updated`,
		other: `Other`,
		owner: `Owner`,
		owners: `Owners`,
		overview: `Overview`,
		pageNotFound: `Page Not Found`,
		pasteFromClipboard: `Paste from Clipboard`,
		percentage: `Percentage`,
		percentageListed: `Percentage Listed`,
		previous: `Previous`,
		profile: `Profile`,
		pixlBalanceInfo: `Your PIXL Balance Will Show Here`,
		pixlHoldings: `PIXL Holdings`,
		stampHoldings: `Stamp Holdings`,
		price: `Price`,
		priceTooLow: `Price Is Too Low`,
		profileCreated: `Profile Created`,
		profileUpdated: `Profile Updated`,
		profileCreatingInfo: `Creating Profile`,
		profileMenu: `Profile Menu`,
		provenanceDetails: `Provenance Details`,
		quantity: `Quantity`,
		quantityMustBeInteger: `Quantity Must Be an Integer`,
		recentActivity: `Recent Activity`,
		recipient: `Recipient`,
		removeAvatar: `Remove Avatar`,
		removeBanner: `Remove Banner`,
		return: `Return`,
		runningUpdate: `Running Update`,
		save: `Save`,
		sell: `Sell`,
		seller: `Seller`,
		sellerFee: `The UCM Will Take a 0.5% Fee from the Total Sale.`,
		setProfilePicture: `Set as Profile Picture`,
		stamp: `Stamp`,
		stampComment: `STAMP Comment`,
		stampCount: `STAMPs`,
		stamped: `Stamped`,
		stampInfo: `STAMP if You Like This Content, STAMPs Generate Rewards for the Creators of an Atomic Asset, Super STAMP if You Want Tip Some of Your STAMP Rewards to the Atomic Asset Sponsors.`,
		stamping: `Stamping`,
		stampSuccess: `Stamped`,
		stampsVouched: `Vouched STAMPs`,
		streak: `Streak`,
		streaks: `Streaks`,
		streakCountdown1: `You Have Approximately`,
		streakCountdown2: `Until You Can Continue Building Your Streak`,
		streakCountdown3: `To Continue Building Your Streak`,
		streakHolders: `Streak Holders`,
		streakLeaderboard: `Streak Leaderboard`,
		streakStart: `Buy an Asset Today to Start Your Streak`,
		streakTitle1: `Start Your Streak`,
		streakTitle2: `Getting Warmer`,
		streakTitle3: `Building the Flame`,
		streakTitle4: `Rising Heat`,
		streakTitle5: `You're on Fire`,
		submit: `Submit`,
		superStamp: `Super STAMP`,
		terms: `Terms`,
		time: `Time`,
		title: `Title`,
		trendingTokens: `Trade FLP Tokens`,
		topCollectors: `Top Collectors`,
		topCreators: `Top Creators`,
		totalAssets: `Total Assets`,
		totalAssetBalance: `Total Asset Balance`,
		totalListingPercentage: `Total Listing Percentage`,
		totalListingQuantity: `Total Listing Quantity`,
		totalPrice: `Total Price`,
		totalPurchasePercentage: `Total Purchase Percentage`,
		totalPurchaseQuantity: `Total Purchase Quantity`,
		totalTransferPercentage: `Total Transfer Percentage`,
		totalTransferQuantity: `Total Transfer Quantity`,
		totalSalesBalance: `Total Balance for Sale`,
		totalSalesPercentage: `Total Percentage for Sale`,
		totalSalesBalanceAvailable: `Total Balance Available for Sale`,
		totalSalesPercentageAvailable: `Total Percentage Available for Sale`,
		totalTransferBalanceAvailable: `Total Balance Available for Transfer`,
		totalTransferPercentageAvailable: `Total Percentage Available for Transfer`,
		tradeAO: `Trade AO`,
		tradePixl: `Trade PIXL`,
		tradePi: `Trade PI`,
		tradeArio: `Trade ARIO`,
		tradeUsda: `Trade USDA`,
		tradeGame: `Trade GAME`,
		tradeWander: `Trade WNDR`,
		tradeStamp: `Trade STAMP`,
		transaction: `Transaction`,
		transfer: `Transfer`,
		transferWar: `Transfer Wrapped AR`,
		transferWander: `Transfer WANDER`,
		selectToken: `Select Token`,
		tokenSelection: `Token Selection`,
		insufficientTokenBalance: `Insufficient Token Balance`,
		tokenValidationError: `Token Validation Error`,
		invalidTokenSelection: `Invalid Token Selection`,
		unitPrice: `Unit Price`,
		updating: `Updating`,
		updatingAsset: `Updating Asset`,
		updatingUCM: `Updating UCM`,
		uploadAvatar: `Upload Avatar`,
		uploadBanner: `Upload Banner`,
		username: `Handle`,
		userConnectedVouched: `You Are Vouched`,
		useDarkDisplay: `Use Dark Display`,
		useLightDisplay: `Use Light Display`,
		view: `View`,
		viewAllCollections: `View All Collections`,
		viewFullBio: `View Full Bio`,
		viewFullDescription: `View Full Description`,
		viewInZenMode: `Zen Mode`,
		viewOnArweave: `View on Arweave`,
		viewProfile: `View Profile`,
	},
};
