export const ARNS_HYDRATE = 'ARNS/HYDRATE';
export const ARNS_FETCH_START = 'ARNS/FETCH_START';
export const ARNS_FETCH_SUCCESS = 'ARNS/FETCH_SUCCESS';
export const ARNS_FETCH_FAILURE = 'ARNS/FETCH_FAILURE';
