export const SET_QUESTS = 'SET_QUESTS';
export const UPDATE_QUEST_PROGRESS = 'UPDATE_QUEST_PROGRESS';
export const COMPLETE_QUEST = 'COMPLETE_QUEST';
export const CLAIM_QUEST_REWARD = 'CLAIM_QUEST_REWARD';
export const SET_QUEST_REWARDS = 'SET_QUEST_REWARDS';
